# Generated by Django 4.0.5 on 2022-11-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_category_alter_recipe_cover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='authors',
            new_name='author',
        ),
    ]
